### ISSUE TITLE
Plugin installation error

### ISSUE THREAD

**Issue by jeanmaack** [SE-Stuttgart/kib3_moodleplugin_srg#2] opened 2023-04-19 11:24 UTC
When i try to install the plugin into moodle that runs on docker, it states the following:
![image](https://user-images.githubusercontent.com/131260758/233060337-a32d5f3e-ed78-4cc0-a002-1db028d858a2.png)

Can you help me fix this?

**Comment by kasrahabib** [comment] 2023-06-05 07:23
Hello @jeanmaack 

Thank you for bringing this to our attention. We have identified the cause of the problem: the .git file was mistakenly included in the repository.

We have addressed this issue and made the necessary changes. Kindly let us know if the problem has been resolved, and we will proceed to close the issue.

Best,
Kasra

**Comment by coderDem** [comment] 2023-06-05 09:52
@kasrahabib thank you for the new version. We could install the plugin in Moodle. This issue can now be closed.

**Closed as completed** 2023-06-06 14:53 UTC
